# Generated by Django 2.2.15 on 2020-08-14 16:05

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'asset_class',
            },
        ),
        migrations.CreateModel(
            name='AssetSubClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'asset_sub_class',
            },
        ),
        migrations.CreateModel(
            name='FeatureCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('asset_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aim.AssetClass')),
                ('asset_sub_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aim.AssetSubClass')),
            ],
            options={
                'db_table': 'feature_code',
            },
        ),
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, help_text='unique asset ID', max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(help_text='Geometry of motor.', srid=4326)),
                ('model', models.CharField(help_text='Model of motor', max_length=64)),
                ('output_hp', models.FloatField(blank=True, help_text='Output HP of motor (SI system)', null=True)),
                ('output_power', models.FloatField(blank=True, help_text='Output HP of motor (SI system)', null=True)),
                ('feature_code', models.ForeignKey(limit_choices_to={'asset_class__name': 'PWS'}, on_delete=django.db.models.deletion.CASCADE, to='aim.FeatureCode')),
            ],
            options={
                'db_table': 'motor',
            },
        ),
        migrations.CreateModel(
            name='MotorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'motor_type',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Administrative code', max_length=128, unique=True)),
                ('name', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'province',
            },
        ),
        migrations.CreateModel(
            name='PumpBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pump_brand',
            },
        ),
        migrations.CreateModel(
            name='PumpType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pump_type',
            },
        ),
        migrations.CreateModel(
            name='SourceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'source_type',
            },
        ),
        migrations.CreateModel(
            name='TankBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tank_brand',
            },
        ),
        migrations.CreateModel(
            name='TankType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tank_type',
            },
        ),
        migrations.CreateModel(
            name='TreatmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'treatment_type',
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, help_text='unique asset ID', max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(help_text='Geometry of tank.', srid=4326)),
                ('feature_code', models.ForeignKey(limit_choices_to={'asset_class__name': 'PWS'}, on_delete=django.db.models.deletion.CASCADE, to='aim.FeatureCode')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aim.TreatmentType')),
            ],
            options={
                'db_table': 'treatment',
            },
        ),
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, help_text='unique asset ID', max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(help_text='Geometry of tank.', srid=4326)),
                ('model', models.CharField(help_text='Model of tank', max_length=64)),
                ('capacity', models.FloatField(blank=True, help_text='Capacity of tank (SI system)', null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aim.TankBrand')),
                ('feature_code', models.ForeignKey(limit_choices_to={'asset_class__name': 'PWS'}, on_delete=django.db.models.deletion.CASCADE, to='aim.FeatureCode')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aim.TankType')),
            ],
            options={
                'db_table': 'tank',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, help_text='unique asset ID', max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(help_text='Geometry of source.', srid=4326)),
                ('feature_code', models.ForeignKey(limit_choices_to={'asset_class__name': 'PWS'}, on_delete=django.db.models.deletion.CASCADE, to='aim.FeatureCode')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aim.SourceType')),
            ],
            options={
                'db_table': 'source',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Administrative code', max_length=128, unique=True)),
                ('name', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True, null=True)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aim.Province')),
            ],
            options={
                'db_table': 'region',
            },
        ),
        migrations.CreateModel(
            name='PumpSubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aim.PumpType')),
            ],
            options={
                'db_table': 'pump_sub_type',
            },
        ),
        migrations.CreateModel(
            name='Pump',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, help_text='unique asset ID', max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(help_text='Geometry of pump.', srid=4326)),
                ('model', models.CharField(help_text='Model of pump', max_length=64)),
                ('submerged', models.BooleanField(blank=True, help_text='Pump is submerged', null=True)),
                ('capacity', models.FloatField(blank=True, help_text='Capacity of pump (SI system)', null=True)),
                ('head', models.FloatField(blank=True, help_text='Head of pump (SI system)', null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aim.PumpBrand')),
                ('feature_code', models.ForeignKey(limit_choices_to={'asset_class__name': 'PWS'}, on_delete=django.db.models.deletion.CASCADE, to='aim.FeatureCode')),
                ('motor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aim.Motor')),
                ('subtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aim.PumpSubType')),
            ],
            options={
                'db_table': 'pump',
            },
        ),
        migrations.AddField(
            model_name='motor',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aim.MotorType'),
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Administrative code', max_length=128, unique=True)),
                ('name', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True, null=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aim.Region')),
            ],
            options={
                'db_table': 'community',
            },
        ),
        migrations.AddField(
            model_name='assetclass',
            name='sub_classes',
            field=models.ManyToManyField(blank=True, to='aim.AssetSubClass'),
        ),
    ]
