# Generated by Django 2.2.5 on 2020-08-14 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'asset_class',
            },
        ),
        migrations.CreateModel(
            name='AssetSubClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'asset_sub_class',
            },
        ),
        migrations.CreateModel(
            name='FeatureCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('asset_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aim.AssetClass')),
                ('asset_sub_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aim.AssetSubClass')),
            ],
            options={
                'db_table': 'feature_code',
            },
        ),
        migrations.AddField(
            model_name='assetclass',
            name='sub_classes',
            field=models.ManyToManyField(blank=True, to='aim.AssetSubClass'),
        ),
    ]
