# Generated by Django 2.2.15 on 2020-08-19 02:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'asset_class',
            },
        ),
        migrations.CreateModel(
            name='AssetSubClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'asset_sub_class',
            },
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, help_text='unique asset ID', max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(help_text='Geometry of Box.', srid=4326)),
                ('model', models.CharField(blank=True, help_text='Model of Box', max_length=256, null=True)),
            ],
            options={
                'db_table': 'box',
            },
        ),
        migrations.CreateModel(
            name='Chamber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, help_text='unique asset ID', max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(help_text='Geometry of Chamber.', srid=4326)),
                ('model', models.CharField(blank=True, help_text='Model of Chamber', max_length=256, null=True)),
            ],
            options={
                'db_table': 'chamber',
            },
        ),
        migrations.CreateModel(
            name='ChamberType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chamber_type',
            },
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Administrative code', max_length=128, unique=True)),
                ('name', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'community',
            },
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'configuration',
            },
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, help_text='unique asset ID', max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'control',
            },
        ),
        migrations.CreateModel(
            name='FeatureCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('asset_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amlit.AssetClass')),
                ('asset_sub_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amlit.AssetSubClass')),
            ],
            options={
                'db_table': 'feature_code',
            },
        ),
        migrations.CreateModel(
            name='Hydrant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, help_text='unique asset ID', max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(help_text='Geometry of tank.', srid=4326)),
                ('model', models.CharField(blank=True, help_text='Model of hydrant', max_length=256, null=True)),
            ],
            options={
                'db_table': 'hydrant',
            },
        ),
        migrations.CreateModel(
            name='HydrantType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hydrant_type',
            },
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, help_text='unique asset ID', max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(help_text='Geometry of Meter.', srid=4326)),
                ('model', models.CharField(blank=True, help_text='Model of Meter', max_length=256, null=True)),
            ],
            options={
                'db_table': 'meter',
            },
        ),
        migrations.CreateModel(
            name='MeterPID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'meter_pid',
            },
        ),
        migrations.CreateModel(
            name='MeterReadingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'meter_reading_type',
            },
        ),
        migrations.CreateModel(
            name='MeterType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'meter_type',
            },
        ),
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, help_text='unique asset ID', max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(help_text='Geometry of motor.', srid=4326)),
                ('model', models.CharField(blank=True, help_text='Model of motor', max_length=256, null=True)),
                ('output_hp', models.FloatField(blank=True, help_text='Output HP of motor (SI system)', null=True)),
                ('output_power', models.FloatField(blank=True, help_text='Output HP of motor (SI system)', null=True)),
                ('control', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amlit.Control')),
                ('feature_code', models.ForeignKey(limit_choices_to={'asset_class__name': 'PWS'}, on_delete=django.db.models.deletion.CASCADE, to='amlit.FeatureCode')),
            ],
            options={
                'db_table': 'motor',
            },
        ),
        migrations.CreateModel(
            name='MotorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'motor_type',
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, help_text='unique asset ID', max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(help_text='Geometry of Part.', srid=4326)),
                ('model', models.CharField(blank=True, help_text='Model of Part', max_length=256, null=True)),
                ('depth', models.FloatField(blank=True, help_text='Depth of part (SI system)', null=True)),
            ],
            options={
                'db_table': 'part',
            },
        ),
        migrations.CreateModel(
            name='PartType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'part_type',
            },
        ),
        migrations.CreateModel(
            name='Pipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, help_text='unique asset ID', max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.LineStringField(help_text='Geometry of Pipe.', srid=4326)),
                ('model', models.CharField(blank=True, help_text='Model of Pipe', max_length=256, null=True)),
                ('diameter', models.FloatField(blank=True, help_text='Depth of pipe (SI system)', null=True)),
                ('depth', models.FloatField(blank=True, help_text='Depth of pipe (SI system)', null=True)),
                ('length', models.FloatField(blank=True, help_text='Length of pipe (SI system)', null=True)),
            ],
            options={
                'db_table': 'pipe',
            },
        ),
        migrations.CreateModel(
            name='PipeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pipe_type',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Administrative code', max_length=128, unique=True)),
                ('name', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'province',
            },
        ),
        migrations.CreateModel(
            name='Pump',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, help_text='unique asset ID', max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(help_text='Geometry of pump.', srid=4326)),
                ('model', models.CharField(blank=True, help_text='Model of pump', max_length=256, null=True)),
                ('submerged', models.BooleanField(blank=True, help_text='Pump is submerged', null=True)),
                ('capacity', models.FloatField(blank=True, help_text='Capacity of pump (SI system)', null=True)),
                ('head', models.FloatField(blank=True, help_text='Head of pump (SI system)', null=True)),
            ],
            options={
                'db_table': 'pump',
            },
        ),
        migrations.CreateModel(
            name='PumpType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pump_type',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, help_text='unique asset ID', max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(help_text='Geometry of source.', srid=4326)),
                ('feature_code', models.ForeignKey(limit_choices_to={'asset_class__name': 'PWS'}, on_delete=django.db.models.deletion.CASCADE, to='amlit.FeatureCode')),
            ],
            options={
                'db_table': 'source',
            },
        ),
        migrations.CreateModel(
            name='SourceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'source_type',
            },
        ),
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, help_text='unique asset ID', max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(help_text='Geometry of tank.', srid=4326)),
                ('model', models.CharField(blank=True, help_text='Model of tank', max_length=256, null=True)),
                ('capacity', models.FloatField(blank=True, help_text='Capacity of tank (SI system)', null=True)),
            ],
            options={
                'db_table': 'tank',
            },
        ),
        migrations.CreateModel(
            name='TankType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tank_type',
            },
        ),
        migrations.CreateModel(
            name='TreatmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'treatment_type',
            },
        ),
        migrations.CreateModel(
            name='Valve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, help_text='unique asset ID', max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(help_text='Geometry of Valve.', srid=4326)),
                ('model', models.CharField(blank=True, help_text='Model of Valve', max_length=256, null=True)),
                ('diameter', models.FloatField(blank=True, help_text='Diameter of valve (SI system)', null=True)),
                ('depth', models.FloatField(blank=True, help_text='Depth of valve (SI system)', null=True)),
            ],
            options={
                'db_table': 'valve',
            },
        ),
        migrations.CreateModel(
            name='ValveActuationDirection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'valve_actuation_direction',
            },
        ),
        migrations.CreateModel(
            name='ValveActuationSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'valve_actuation_spec',
            },
        ),
        migrations.CreateModel(
            name='ValveActuationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'valve_actuation_type',
            },
        ),
        migrations.CreateModel(
            name='ValveType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'valve_type',
            },
        ),
        migrations.CreateModel(
            name='WaterGeneralBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'water_general_brand',
            },
        ),
        migrations.CreateModel(
            name='WaterGeneralMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'water_general_material',
            },
        ),
        migrations.CreateModel(
            name='WaterSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('boxes', models.ManyToManyField(blank=True, to='amlit.Box')),
                ('chamber', models.ManyToManyField(blank=True, to='amlit.Chamber')),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amlit.Community')),
                ('control', models.ManyToManyField(blank=True, to='amlit.Control')),
                ('hydrant', models.ManyToManyField(blank=True, to='amlit.Hydrant')),
                ('meter', models.ManyToManyField(blank=True, to='amlit.Meter')),
                ('motor', models.ManyToManyField(blank=True, to='amlit.Motor')),
                ('part', models.ManyToManyField(blank=True, to='amlit.Part')),
                ('pipe', models.ManyToManyField(blank=True, to='amlit.Pipe')),
                ('pump', models.ManyToManyField(blank=True, to='amlit.Pump')),
                ('source', models.ManyToManyField(blank=True, to='amlit.Source')),
                ('tank', models.ManyToManyField(blank=True, to='amlit.Tank')),
                ('valve', models.ManyToManyField(blank=True, to='amlit.Valve')),
            ],
            options={
                'db_table': 'water_system',
            },
        ),
        migrations.AddField(
            model_name='valve',
            name='actuation_direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amlit.ValveActuationDirection'),
        ),
        migrations.AddField(
            model_name='valve',
            name='actuation_spec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amlit.ValveActuationSpec'),
        ),
        migrations.AddField(
            model_name='valve',
            name='actuation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amlit.ValveActuationType'),
        ),
        migrations.AddField(
            model_name='valve',
            name='box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amlit.Box'),
        ),
        migrations.AddField(
            model_name='valve',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amlit.WaterGeneralBrand'),
        ),
        migrations.AddField(
            model_name='valve',
            name='feature_code',
            field=models.ForeignKey(limit_choices_to={'asset_class__name': 'PWS'}, on_delete=django.db.models.deletion.CASCADE, to='amlit.FeatureCode'),
        ),
        migrations.AddField(
            model_name='valve',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amlit.ValveType'),
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, help_text='unique asset ID', max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(help_text='Geometry of tank.', srid=4326)),
                ('feature_code', models.ForeignKey(limit_choices_to={'asset_class__name': 'PWS'}, on_delete=django.db.models.deletion.CASCADE, to='amlit.FeatureCode')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amlit.TreatmentType')),
            ],
            options={
                'db_table': 'treatment',
            },
        ),
        migrations.AddField(
            model_name='tank',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amlit.WaterGeneralBrand'),
        ),
        migrations.AddField(
            model_name='tank',
            name='feature_code',
            field=models.ForeignKey(limit_choices_to={'asset_class__name': 'PWS'}, on_delete=django.db.models.deletion.CASCADE, to='amlit.FeatureCode'),
        ),
        migrations.AddField(
            model_name='tank',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amlit.TankType'),
        ),
        migrations.AddField(
            model_name='source',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amlit.SourceType'),
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Administrative code', max_length=128, unique=True)),
                ('name', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True, null=True)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amlit.Province')),
            ],
            options={
                'db_table': 'region',
            },
        ),
        migrations.CreateModel(
            name='PumpSubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amlit.PumpType')),
            ],
            options={
                'db_table': 'pump_sub_type',
            },
        ),
        migrations.AddField(
            model_name='pump',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amlit.WaterGeneralBrand'),
        ),
        migrations.AddField(
            model_name='pump',
            name='feature_code',
            field=models.ForeignKey(limit_choices_to={'asset_class__name': 'PWS'}, on_delete=django.db.models.deletion.CASCADE, to='amlit.FeatureCode'),
        ),
        migrations.AddField(
            model_name='pump',
            name='motor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amlit.Motor'),
        ),
        migrations.AddField(
            model_name='pump',
            name='subtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amlit.PumpSubType'),
        ),
        migrations.AddField(
            model_name='pipe',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amlit.WaterGeneralBrand'),
        ),
        migrations.AddField(
            model_name='pipe',
            name='feature_code',
            field=models.ForeignKey(limit_choices_to={'asset_class__name': 'PWS'}, on_delete=django.db.models.deletion.CASCADE, to='amlit.FeatureCode'),
        ),
        migrations.AddField(
            model_name='pipe',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amlit.WaterGeneralMaterial'),
        ),
        migrations.AddField(
            model_name='pipe',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amlit.PipeType'),
        ),
        migrations.AddField(
            model_name='part',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amlit.WaterGeneralBrand'),
        ),
        migrations.AddField(
            model_name='part',
            name='feature_code',
            field=models.ForeignKey(limit_choices_to={'asset_class__name': 'PWS'}, on_delete=django.db.models.deletion.CASCADE, to='amlit.FeatureCode'),
        ),
        migrations.AddField(
            model_name='part',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amlit.WaterGeneralMaterial'),
        ),
        migrations.AddField(
            model_name='part',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amlit.PartType'),
        ),
        migrations.AddField(
            model_name='motor',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amlit.MotorType'),
        ),
        migrations.AddField(
            model_name='meter',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amlit.WaterGeneralBrand'),
        ),
        migrations.AddField(
            model_name='meter',
            name='feature_code',
            field=models.ForeignKey(limit_choices_to={'asset_class__name': 'PWS'}, on_delete=django.db.models.deletion.CASCADE, to='amlit.FeatureCode'),
        ),
        migrations.AddField(
            model_name='meter',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amlit.MeterPID'),
        ),
        migrations.AddField(
            model_name='meter',
            name='reading_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amlit.MeterReadingType'),
        ),
        migrations.AddField(
            model_name='meter',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amlit.MeterType'),
        ),
        migrations.AddField(
            model_name='hydrant',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amlit.WaterGeneralBrand'),
        ),
        migrations.AddField(
            model_name='hydrant',
            name='feature_code',
            field=models.ForeignKey(limit_choices_to={'asset_class__name': 'PWS'}, on_delete=django.db.models.deletion.CASCADE, to='amlit.FeatureCode'),
        ),
        migrations.AddField(
            model_name='hydrant',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amlit.HydrantType'),
        ),
        migrations.AddField(
            model_name='control',
            name='feature_code',
            field=models.ForeignKey(limit_choices_to={'asset_class__name': 'PWS'}, on_delete=django.db.models.deletion.CASCADE, to='amlit.FeatureCode'),
        ),
        migrations.AddField(
            model_name='community',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amlit.Region'),
        ),
        migrations.AddField(
            model_name='chamber',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amlit.WaterGeneralBrand'),
        ),
        migrations.AddField(
            model_name='chamber',
            name='feature_code',
            field=models.ForeignKey(limit_choices_to={'asset_class__name': 'PWS'}, on_delete=django.db.models.deletion.CASCADE, to='amlit.FeatureCode'),
        ),
        migrations.AddField(
            model_name='chamber',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amlit.ChamberType'),
        ),
        migrations.AddField(
            model_name='box',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amlit.WaterGeneralBrand'),
        ),
        migrations.AddField(
            model_name='box',
            name='feature_code',
            field=models.ForeignKey(limit_choices_to={'asset_class__name': 'PWS'}, on_delete=django.db.models.deletion.CASCADE, to='amlit.FeatureCode'),
        ),
        migrations.AddField(
            model_name='box',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amlit.WaterGeneralMaterial'),
        ),
        migrations.AddField(
            model_name='assetclass',
            name='sub_classes',
            field=models.ManyToManyField(blank=True, to='amlit.AssetSubClass'),
        ),
    ]
