# Generated by Django 2.2.15 on 2020-08-19 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amlit', '0002_initial_feature_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watersystem',
            old_name='chamber',
            new_name='chambers',
        ),
        migrations.RenameField(
            model_name='watersystem',
            old_name='control',
            new_name='controls',
        ),
        migrations.RenameField(
            model_name='watersystem',
            old_name='hydrant',
            new_name='hydrants',
        ),
        migrations.RenameField(
            model_name='watersystem',
            old_name='meter',
            new_name='meters',
        ),
        migrations.RenameField(
            model_name='watersystem',
            old_name='motor',
            new_name='motors',
        ),
        migrations.RenameField(
            model_name='watersystem',
            old_name='part',
            new_name='parts',
        ),
        migrations.RenameField(
            model_name='watersystem',
            old_name='pipe',
            new_name='pipes',
        ),
        migrations.RenameField(
            model_name='watersystem',
            old_name='pump',
            new_name='pumps',
        ),
        migrations.RenameField(
            model_name='watersystem',
            old_name='source',
            new_name='sources',
        ),
        migrations.RenameField(
            model_name='watersystem',
            old_name='tank',
            new_name='tanks',
        ),
        migrations.RenameField(
            model_name='watersystem',
            old_name='valve',
            new_name='valves',
        ),
    ]
