# Generated by Django 2.2.15 on 2021-04-16 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0007_2_4'),
        ('amlit', '0004_auto_20210416_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organisation_subscription', to='djstripe.Subscription', verbose_name='Subscription'),
        ),
    ]
